# Generated by Django 3.0.5 on 2020-04-14 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('APPOINT_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('APPOINT_NAME', models.CharField(blank=True, max_length=25, null=True)),
                ('l1', models.IntegerField(blank=True, default=None, null=True)),
                ('l2', models.IntegerField(blank=True, default=None, null=True)),
                ('l3', models.IntegerField(blank=True, default=None, null=True)),
                ('l4', models.IntegerField(blank=True, default=None, null=True)),
                ('l5', models.IntegerField(blank=True, default=None, null=True)),
                ('l6', models.IntegerField(blank=True, default=None, null=True)),
                ('l7', models.IntegerField(blank=True, default=None, null=True)),
                ('l8', models.IntegerField(blank=True, default=None, null=True)),
                ('l9', models.IntegerField(blank=True, default=None, null=True)),
                ('l10', models.IntegerField(blank=True, default=None, null=True)),
                ('l11', models.IntegerField(blank=True, default=None, null=True)),
                ('l12', models.IntegerField(blank=True, default=None, null=True)),
                ('l13', models.IntegerField(blank=True, default=None, null=True)),
                ('l14', models.IntegerField(blank=True, default=None, null=True)),
                ('l15', models.IntegerField(blank=True, default=None, null=True)),
                ('D1', models.IntegerField(blank=True, default=None, null=True)),
                ('D2', models.IntegerField(blank=True, default=None, null=True)),
                ('D3', models.IntegerField(blank=True, default=None, null=True)),
                ('D4', models.IntegerField(blank=True, default=None, null=True)),
                ('D5', models.IntegerField(blank=True, default=None, null=True)),
                ('D6', models.IntegerField(blank=True, default=None, null=True)),
                ('D7', models.IntegerField(blank=True, default=None, null=True)),
                ('D8', models.IntegerField(blank=True, default=None, null=True)),
                ('D9', models.IntegerField(blank=True, default=None, null=True)),
                ('D10', models.IntegerField(blank=True, default=None, null=True)),
                ('D11', models.IntegerField(blank=True, default=None, null=True)),
                ('D12', models.IntegerField(blank=True, default=None, null=True)),
                ('D13', models.IntegerField(blank=True, default=None, null=True)),
                ('D14', models.IntegerField(blank=True, default=None, null=True)),
                ('D15', models.IntegerField(blank=True, default=None, null=True)),
                ('D16', models.IntegerField(blank=True, default=None, null=True)),
                ('D17', models.IntegerField(blank=True, default=None, null=True)),
                ('D18', models.IntegerField(blank=True, default=None, null=True)),
                ('D19', models.IntegerField(blank=True, default=None, null=True)),
                ('D20', models.IntegerField(blank=True, default=None, null=True)),
                ('D21', models.IntegerField(blank=True, default=None, null=True)),
                ('D22', models.IntegerField(blank=True, default=None, null=True)),
                ('D23', models.IntegerField(blank=True, default=None, null=True)),
                ('D24', models.IntegerField(blank=True, default=None, null=True)),
                ('D25', models.IntegerField(blank=True, default=None, null=True)),
                ('D26', models.IntegerField(blank=True, default=None, null=True)),
                ('D27', models.IntegerField(blank=True, default=None, null=True)),
                ('D28', models.IntegerField(blank=True, default=None, null=True)),
                ('D29', models.IntegerField(blank=True, default=None, null=True)),
                ('D30', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'APPOINT',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('BNO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('BSNAME', models.CharField(blank=True, max_length=10, null=True)),
                ('BNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('LOCATION', models.CharField(blank=True, max_length=35, null=True)),
                ('BANKNO', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'BANK',
            },
        ),
        migrations.CreateModel(
            name='Bank_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'BANK_NAME',
            },
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('CASTE_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('CASTE_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'CASTE',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CATEGORY_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('CATEGORY_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CITY_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('CITY_NAME', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'CITY',
            },
        ),
        migrations.CreateModel(
            name='Designation_Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'DESIGNATION_NATURE',
            },
        ),
        migrations.CreateModel(
            name='Designature',
            fields=[
                ('DESIGNATURE_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('DESIGNATURE_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'DESIGNATURE',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_NUMBER', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('SEQUENCE_NUMBER', models.CharField(blank=True, max_length=50, null=True)),
                ('TITLE', models.CharField(blank=True, max_length=50, null=True)),
                ('FIRST_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('FATHER_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('INCREMENT_DATE', models.DateField()),
                ('DATE_OF_BIRTH', models.DateField()),
                ('DATE_OF_JOINING', models.DateField()),
                ('DATE_OF_RETIREMENT', models.DateField()),
                ('DESIGNATION_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('GENDER', models.CharField(blank=True, max_length=50, null=True)),
                ('TA', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('PT', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, max_length=10, null=True)),
                ('QUARTER', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True)),
                ('RENT_FREE', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True)),
                ('QUARTER_ADDRESS', models.CharField(blank=True, max_length=50, null=True)),
                ('HANDICAP', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True)),
                ('SENIOR_CITIZEN', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True)),
                ('DESIGNATION', models.CharField(blank=True, max_length=50, null=True)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=50, null=True)),
                ('STAFF_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('APPOINTMENT', models.CharField(blank=True, max_length=50, null=True)),
                ('VACATIONAL', models.CharField(blank=True, max_length=50, null=True)),
                ('BANK_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('BANK_ACCOUNT_NUMBER', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='INVALID ACCOUNT NUMBER', regex='^\\d{9,18}$')])),
                ('PF_NUMBER', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='INVALID PF NUMBER', regex='^[A-Z]{2}/[A-Z]{3}/\\d{5}/\\d{3}/\\d{7}$')])),
                ('PRAN_NUMBER', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='INVALID PF NUMBER', regex='^\\d{12,12}$')])),
                ('PAN_NUMBER', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='INVALID PAN NUMBER', regex='^([a-zA-Z]){5}([0-9]){4}([a-zA-Z]){1}?$')])),
                ('UNDER', models.CharField(blank=True, max_length=50, null=True)),
                ('LEVEL', models.CharField(blank=True, max_length=50, null=True)),
                ('BASIC', models.IntegerField()),
                ('PAY_STATUS', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('RULE', models.CharField(blank=True, max_length=50, null=True)),
                ('REMARK', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'EmployeeInformation',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'GENDER',
            },
        ),
        migrations.CreateModel(
            name='InstallmentType',
            fields=[
                ('INO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('IDNO', models.IntegerField(blank=True, default=None, null=True)),
                ('PAYHEAD', models.CharField(blank=True, max_length=3, null=True)),
                ('MONAMT', models.IntegerField(blank=True, default=None, null=True)),
                ('INSTALNO', models.IntegerField(blank=True, default=None, null=True)),
                ('TOTAMT', models.IntegerField(blank=True, default=None, null=True)),
                ('REM', models.CharField(blank=True, max_length=200, null=True)),
                ('STOP', models.IntegerField(blank=True, default=None, null=True)),
                ('EXPDT', models.DateTimeField(auto_now_add=True)),
                ('PAIDNO', models.IntegerField(blank=True, default=None, null=True)),
                ('MON', models.CharField(blank=True, max_length=7, null=True)),
                ('NEW', models.IntegerField(blank=True, default=None, null=True)),
                ('REF_NO', models.CharField(blank=True, max_length=35, null=True)),
                ('DESP_NO', models.CharField(blank=True, max_length=35, null=True)),
                ('DESP_DT', models.DateTimeField(auto_now_add=True)),
                ('START_DT', models.DateTimeField(auto_now_add=True)),
                ('DEFA_AMT', models.IntegerField(blank=True, default=None, null=True)),
                ('PRO_AMT', models.IntegerField(blank=True, default=None, null=True)),
                ('CODE', models.CharField(blank=True, max_length=20, null=True)),
                ('IBNO', models.IntegerField(blank=True, default=None, null=True)),
                ('MONYEAR', models.CharField(blank=True, max_length=30, null=True)),
                ('STOP1', models.IntegerField(blank=True, default=None, null=True)),
                ('BAL_AMT', models.IntegerField(blank=True, default=None, null=True)),
                ('REGULAR', models.IntegerField(blank=True, default=None, null=True)),
                ('LTNO', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'INSTALLMENT',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'LEVEL',
            },
        ),
        migrations.CreateModel(
            name='MainDept',
            fields=[
                ('DEPT_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('DEPT_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('SDEPT', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='MainDesignation',
            fields=[
                ('DESIG_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('DESIG_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('SDESIG', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'DESIGNATION',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('RELIGION_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('RELIGION_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'RELIGION',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'RULE',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('SCALE_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('B1', models.IntegerField(blank=True, default=None, null=True)),
                ('l1', models.IntegerField(blank=True, default=None, null=True)),
                ('B2', models.IntegerField(blank=True, default=None, null=True)),
                ('l2', models.IntegerField(blank=True, default=None, null=True)),
                ('B3', models.IntegerField(blank=True, default=None, null=True)),
                ('l3', models.IntegerField(blank=True, default=None, null=True)),
                ('B4', models.IntegerField(blank=True, default=None, null=True)),
                ('l4', models.IntegerField(blank=True, default=None, null=True)),
                ('SCALE_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('l5', models.IntegerField(blank=True, default=None, null=True)),
                ('DETAIL', models.CharField(blank=True, max_length=200, null=True)),
                ('GRDPAY', models.IntegerField(blank=True, default=None, null=True)),
                ('PAYBAND', models.CharField(blank=True, max_length=60, null=True)),
                ('TA', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'SCALE',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('STAFF_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('STAFF_NAME', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'STAFF',
            },
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('STNO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('STAFF_TYPE', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'STAFFTYPE',
            },
        ),
        migrations.CreateModel(
            name='SuplHead',
            fields=[
                ('SUPLNO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('SUPLHEAD_NAME', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'SUPLHEAD',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('TITLE_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('TITLE_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'TITLE',
            },
        ),
        migrations.CreateModel(
            name='TypeTran',
            fields=[
                ('TYPETRAN_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('TYPETRAN_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'TYPETRAN',
            },
        ),
        migrations.CreateModel(
            name='Under',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'UNDER',
            },
        ),
        migrations.CreateModel(
            name='UnderCollege',
            fields=[
                ('UNO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('UGPG_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('LUGPG', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UGPG',
            },
        ),
        migrations.CreateModel(
            name='Vacational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'VACATIONAL',
            },
        ),
        migrations.CreateModel(
            name='SubDesignation',
            fields=[
                ('SUBDESIG_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('SUBDESIG_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('SUBDESIG', models.CharField(blank=True, max_length=8, null=True)),
                ('DESIG_NO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.MainDesignation')),
            ],
            options={
                'db_table': 'SUBDESIG',
            },
        ),
        migrations.CreateModel(
            name='SubDept',
            fields=[
                ('SUBDEPT_NO', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('SUBDEPT_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('SUBDEPT', models.CharField(blank=True, max_length=10, null=True)),
                ('DEPT_NO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.MainDept')),
            ],
            options={
                'db_table': 'SUBDEPT',
            },
        ),
    ]
