# Generated by Django 3.0.5 on 2020-04-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='RELIGION_NO',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
