# Generated by Django 2.2.5 on 2020-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPOINT_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('APPOINT_NAME', models.CharField(blank=True, max_length=25, null=True)),
                ('l1', models.IntegerField(blank=True, default=None, null=True)),
                ('l2', models.IntegerField(blank=True, default=None, null=True)),
                ('l3', models.IntegerField(blank=True, default=None, null=True)),
                ('l4', models.IntegerField(blank=True, default=None, null=True)),
                ('l5', models.IntegerField(blank=True, default=None, null=True)),
                ('l6', models.IntegerField(blank=True, default=None, null=True)),
                ('l7', models.IntegerField(blank=True, default=None, null=True)),
                ('l8', models.IntegerField(blank=True, default=None, null=True)),
                ('l9', models.IntegerField(blank=True, default=None, null=True)),
                ('l10', models.IntegerField(blank=True, default=None, null=True)),
                ('l11', models.IntegerField(blank=True, default=None, null=True)),
                ('l12', models.IntegerField(blank=True, default=None, null=True)),
                ('l13', models.IntegerField(blank=True, default=None, null=True)),
                ('l14', models.IntegerField(blank=True, default=None, null=True)),
                ('l15', models.IntegerField(blank=True, default=None, null=True)),
                ('D1', models.IntegerField(blank=True, default=None, null=True)),
                ('D2', models.IntegerField(blank=True, default=None, null=True)),
                ('D3', models.IntegerField(blank=True, default=None, null=True)),
                ('D4', models.IntegerField(blank=True, default=None, null=True)),
                ('D5', models.IntegerField(blank=True, default=None, null=True)),
                ('D6', models.IntegerField(blank=True, default=None, null=True)),
                ('D7', models.IntegerField(blank=True, default=None, null=True)),
                ('D8', models.IntegerField(blank=True, default=None, null=True)),
                ('D9', models.IntegerField(blank=True, default=None, null=True)),
                ('D10', models.IntegerField(blank=True, default=None, null=True)),
                ('D11', models.IntegerField(blank=True, default=None, null=True)),
                ('D12', models.IntegerField(blank=True, default=None, null=True)),
                ('D13', models.IntegerField(blank=True, default=None, null=True)),
                ('D14', models.IntegerField(blank=True, default=None, null=True)),
                ('D15', models.IntegerField(blank=True, default=None, null=True)),
                ('D16', models.IntegerField(blank=True, default=None, null=True)),
                ('D17', models.IntegerField(blank=True, default=None, null=True)),
                ('D18', models.IntegerField(blank=True, default=None, null=True)),
                ('D19', models.IntegerField(blank=True, default=None, null=True)),
                ('D20', models.IntegerField(blank=True, default=None, null=True)),
                ('D21', models.IntegerField(blank=True, default=None, null=True)),
                ('D22', models.IntegerField(blank=True, default=None, null=True)),
                ('D23', models.IntegerField(blank=True, default=None, null=True)),
                ('D24', models.IntegerField(blank=True, default=None, null=True)),
                ('D25', models.IntegerField(blank=True, default=None, null=True)),
                ('D26', models.IntegerField(blank=True, default=None, null=True)),
                ('D27', models.IntegerField(blank=True, default=None, null=True)),
                ('D28', models.IntegerField(blank=True, default=None, null=True)),
                ('D29', models.IntegerField(blank=True, default=None, null=True)),
                ('D30', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'APPOINT',
            },
        ),
        migrations.CreateModel(
            name='InstallmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INO', models.IntegerField(blank=True, default=None, null=True)),
                ('IDNO', models.IntegerField(blank=True, default=None, null=True)),
                ('PAYHEAD', models.CharField(blank=True, max_length=3, null=True)),
                ('MONAMT', models.IntegerField(blank=True, default=None, null=True)),
                ('INSTALNO', models.IntegerField(blank=True, default=None, null=True)),
                ('TOTAMT', models.IntegerField(blank=True, default=None, null=True)),
                ('REM', models.CharField(blank=True, max_length=200, null=True)),
                ('STOP', models.IntegerField(blank=True, default=None, null=True)),
                ('PAIDNO', models.IntegerField(blank=True, default=None, null=True)),
                ('MON', models.CharField(blank=True, max_length=7, null=True)),
                ('NEW', models.IntegerField(blank=True, default=None, null=True)),
                ('REF_NO', models.CharField(blank=True, max_length=35, null=True)),
                ('DESP_NO', models.CharField(blank=True, max_length=35, null=True)),
                ('DEFA_AMT', models.IntegerField(blank=True, default=None, null=True)),
                ('PRO_AMT', models.IntegerField(blank=True, default=None, null=True)),
                ('CODE', models.CharField(blank=True, max_length=20, null=True)),
                ('IBNO', models.IntegerField(blank=True, default=None, null=True)),
                ('MONYEAR', models.CharField(blank=True, max_length=30, null=True)),
                ('STOP1', models.IntegerField(blank=True, default=None, null=True)),
                ('BAL_AMT', models.IntegerField(blank=True, default=None, null=True)),
                ('REGULAR', models.IntegerField(blank=True, default=None, null=True)),
                ('LTNO', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'INSTALLMENT',
            },
        ),
        migrations.CreateModel(
            name='MainDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPT_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('DEPT_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('SDEPT', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='MainDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESIG_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('DESIG_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('SDESIG', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'DESIGNATION',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCALE_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('B1', models.IntegerField(blank=True, default=None, null=True)),
                ('l1', models.IntegerField(blank=True, default=None, null=True)),
                ('B2', models.IntegerField(blank=True, default=None, null=True)),
                ('l2', models.IntegerField(blank=True, default=None, null=True)),
                ('B3', models.IntegerField(blank=True, default=None, null=True)),
                ('l3', models.IntegerField(blank=True, default=None, null=True)),
                ('B4', models.IntegerField(blank=True, default=None, null=True)),
                ('l4', models.IntegerField(blank=True, default=None, null=True)),
                ('SCALE_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('l5', models.IntegerField(blank=True, default=None, null=True)),
                ('DETAIL', models.CharField(blank=True, max_length=200, null=True)),
                ('GRDPAY', models.IntegerField(blank=True, default=None, null=True)),
                ('PAYBAND', models.CharField(blank=True, max_length=60, null=True)),
                ('TA', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'SCALE',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAFF_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('STAFF_NAME', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'STAFF',
            },
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STNO', models.IntegerField(blank=True, default=None, null=True)),
                ('STAFF_TYPE', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'STAFFTYPE',
            },
        ),
        migrations.CreateModel(
            name='SubDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBDEPT_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('SUBDEPT_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('SUBDEPT', models.CharField(blank=True, max_length=10, null=True)),
                ('DEPT_NO', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'SUBDEPT',
            },
        ),
        migrations.CreateModel(
            name='SubDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBDESIG_NO', models.IntegerField(blank=True, default=None, null=True)),
                ('SUBDESIG_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('SUBDESIG', models.CharField(blank=True, max_length=8, null=True)),
                ('DESIG_NO', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'SUBDESIG',
            },
        ),
        migrations.CreateModel(
            name='UnderCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNO', models.IntegerField(blank=True, default=None, null=True)),
                ('UGPG_NAME', models.CharField(blank=True, max_length=20, null=True)),
                ('LUGPG', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UGPG',
            },
        ),
    ]
