# Generated by Django 3.0.4 on 2020-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20200414_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='SCALE_NO',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
