# Generated by Django 3.0.5 on 2020-04-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20200402_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
